version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - DATABASE_URI=sqlite:///exams.db
    volumes:
      - ./uploads:/app/uploads
      - ./exams.db:/app/exams.db
    restart: unless-stopped
    command: python app.py
